chore: setup frontend
eve0415/SONBIN pull request #1
Opened 2024-08-20 16:56 UTC by Yusuke4869

FEの環境を構築した

- react
- wouter
- tailwindcss
- vite
- eslint
- prettier

2024-08-20 23:38 UTC, eve0415 requested changes

2024-08-20 23:38 UTC, eve0415 commented on .github/workflows/frontend.yaml
> +        run: pnpm run lint:ci
`package.json` に書かずに、ここに直接書いて
そして、eslint と prettier 分けて

2024-08-20 23:38 UTC, eve0415 commented on .github/workflows/frontend.yaml
> +        run: pnpm run build
```suggestion
        run: pnpm build
```

2024-08-20 23:38 UTC, eve0415 commented on .github/workflows/frontend.yaml
> +          node-version-file: package.json
```suggestion
          cache: pnpm
```

2024-08-20 23:38 UTC, eve0415 commented on .github/workflows/frontend.yaml
> +        uses: actions/setup-node@main
```suggestion
        uses: actions/setup-node@v4
```

2024-08-20 23:38 UTC, eve0415 commented on .github/workflows/frontend.yaml
無料だから、並列で動くようにしていいよ

2024-08-20 23:38 UTC, eve0415 commented on eslint.config.js
> +/* eslint-disable @typescript-eslint/no-unsafe-argument */
なんのため？

2024-08-20 23:38 UTC, eve0415 commented on tsconfig.json
`verbatimModuleSyntax` を `true` に
`noUncheckedIndexedAccess` を `true` に

2024-08-20 23:38 UTC, eve0415 commented
返った、残り見る

2024-08-21 03:57 UTC, Yusuke4869 commented on eslint.config.js
> +/* eslint-disable @typescript-eslint/no-unsafe-argument */
これがないとESLintのExtensionがこのファイルでエラーを吐くんですよね

2024-08-22 01:56 UTC, eve0415 requested changes

2024-08-22 01:56 UTC, eve0415 commented on .github/workflows/frontend.yaml
> +  format:
job ごとに 改行入れて欲しい

2024-08-22 01:56 UTC, eve0415 commented on .github/workflows/frontend.yaml
> +name: Frontend
```suggestion
name: Frontend Tests
```

2024-08-22 01:56 UTC, eve0415 commented on .github/workflows/frontend.yaml
> +      - name: Link Check
```suggestion
      - name: Check
```

2024-08-22 01:56 UTC, eve0415 commented on .github/workflows/frontend.yaml
> +      - name: Format Check
```suggestion
      - name: Check
```

2024-08-22 01:56 UTC, eve0415 commented on .github/workflows/frontend.yaml
> +      - name: Build Check
```suggestion
      - name: Check
```

2024-08-22 01:56 UTC, eve0415 commented on frontend/pages/index.ts
BarrelFile は好きくない

2024-08-22 01:56 UTC, eve0415 commented on tsconfig.json
> +  "include": ["frontend", "**/*.js", "**/*.ts", "**/*.tsx"],
```suggestion
  "include": ["frontend", "*.js", "*.ts"],
```

2024-08-23 01:03 UTC, eve0415 approved these changes, later dismissed
とりあえず ok

2024-08-23 01:04 UTC, eve0415 commented
[frontend/pages/index.ts](https://github.com/eve0415/SONBIN/pull/1/files/90bbd248b79091d310a9c38a253db483bd4d66ae#diff-f8b536efc8cb2e4f54b2182f212a4ddbf29ccfc06232ce0fc310872a0337d74f)

ここに `export * from '<file path>'` をたくさん書いてく感じ？

2024-08-23 03:00 UTC, Yusuke4869 commented
あ、疲れ切ってて消すの忘れてました
BarrelFile は個人的にあってもなくてもいいので消します

2024-08-23 08:53 UTC, eve0415 approved these changes

2024-08-23 08:53 UTC, merged