feat(bingo): generate and judge bingo board
eve0415/SONBIN pull request #8
Opened 2024-08-26 17:12 UTC by Allianaab2m

- ビンゴ盤を生成する
- そのビンゴ盤がリーチ・ビンゴかどうか判定する
- 判定・生成に必要な行列系メソッドの実装

2024-08-26 22:58 UTC, eve0415 requested changes
`server` パッケージから見れる必要があるものについては、`pub`
見れなくていいもの（触らない方がいい、触って欲しくないもの)は、`pub(crate)` 使ってください

2024-08-26 22:58 UTC, eve0415 commented on backend/bingo/src/board.rs
> +        }
これだと、今開けたところでビンゴになったかリーチになったかわからなくない？

2024-08-26 22:58 UTC, eve0415 commented on backend/bingo/src/generate.rs
> +pub fn board_numbers(rng: &mut StdRng, size: usize) -> Vec<Vec<usize>> {
前置詞として、generate とか create とかの単語が欲しい

2024-08-26 22:58 UTC, eve0415 commented on backend/bingo/src/generate.rs
> +    }
パニック起こすと困るので、普通に `Result` 使って、ここは `Err` を使用してください

2024-08-26 22:58 UTC, eve0415 commented on backend/bingo/src/generate.rs
> +    fn generate_number() {
```suggestion
    fn it_can_generate_numbers() {
```

⚪︎⚪︎ができる！みたいなテスト名にして欲しいです

2024-08-27 05:54 UTC, Allianaab2m commented on backend/bingo/src/board.rs
> +        }
確かに どうやって判定するのがいいですかね

2024-08-27 06:21 UTC, eve0415 commented on backend/bingo/src/board.rs
> +        }
`judge_bingo` を新たな引数を渡す拡張するか、返り値に開けた数字が入ってるかをチェックするか

2024-08-27 06:21 UTC, eve0415 commented on backend/bingo/src/board.rs
> +        }
いや、リーチ判定も行いたいから、ここで似た実装をするかとか？
開けた数字を元に縦、横、（斜め）が全部空いてる数字になったかどうか、リーチになったかどうかを判定するロジックを入れる方が得策かも

2024-08-27 06:25 UTC, eve0415 commented on backend/bingo/src/generate.rs
> +    fn generate_number() {
他のテストケースも同様に対処お願いします

2024-09-06 12:35 UTC, eve0415 commented
一旦このままマージして、続き実装しちゃいますまる

2024-09-06 13:05 UTC, eve0415 approved these changes

2024-09-06 13:07 UTC, Allianaab2m commented
お願いします :pray:

2024-09-06 13:14 UTC, merged